Add PyTorch vLLM Latency tests

diff --git a/.azuredevops/templates/test_pytorch-vllm.yml b/.azuredevops/templates/test_pytorch-vllm.yml
--- a/.azuredevops/templates/test_pytorch-vllm.yml
+++ b/.azuredevops/templates/test_pytorch-vllm.yml
@@ -1,6 +1,6 @@
 steps:
   - task: Bash@3
-    displayName: PyTorch Tests
+    displayName: PyTorch vLLM Latency Tests
     env:
       BINARIES_DIR: $(Build.BinariesDirectory)
       PIPELINE_WORKSPACE: $(Pipeline.Workspace)
@@ -8,7 +8,7 @@ steps:
       targetType: inline
       script: |
         echo "Submitting test job..."
-        TEST_JOB_ID=$(sbatch --export=ALL --parsable $(Build.SourcesDirectory)/.azuredevops/slurm/test_pytorch-tests.sh)
+        TEST_JOB_ID=$(sbatch --export=ALL --parsable $(Build.SourcesDirectory)/.azuredevops/slurm/test_pytorch-vllm.sh)
         echo "Submitted test job: $TEST_JOB_ID"
         echo "##vso[task.setvariable variable=TEST_JOB_ID]$TEST_JOB_ID"
 
@@ -20,7 +20,7 @@ steps:
 
         echo "Waiting for final status via sacct..."
         LOOP_COUNT=0
-        MAX_LOOPS=300  # Maximum of 300 loops (300 minutes)
+        MAX_LOOPS=120  # Maximum of 120 loops (120 minutes)
         while true; do
           STATE=$(sacct -j "$TEST_JOB_ID" --format=JobID,State --noheader | awk '$1 ~ /\.batch$/ { print $2; exit }' | xargs)
           echo "##[section]Test job state: $STATE"
@@ -38,32 +38,48 @@ steps:
           fi
         done
 
-        echo "Checking test result XML for failures..."
-        TEST_XML=$(find "$(Pipeline.Workspace)" -name 'pytorch_test*.xml')
-        if [ -z "$TEST_XML" ]; then
-          echo "##vso[task.logissue type=error]No $TEST_XML file found"
+        echo "Checking test result logs for failures..."
+        TEST_LOG=$(find "$(Pipeline.Workspace)" -name 'pytorch_vllm_results.log')
+        if [ -z "$TEST_LOG" ]; then
+          echo "##vso[task.logissue type=error]No $TEST_LOG file found"
           echo "##vso[task.complete result=Failed;]DONE"
           exit 1
         fi
 
-        if grep -q 'failures="[^0]' "$TEST_XML"; then
-          echo "##vso[task.logissue type=error]Test failures detected in $TEST_XML"
+        if grep -q 'failures="[^0]' "$TEST_LOG"; then
+          echo "##vso[task.logissue type=error]Test failures detected in $TEST_LOG"
           echo "##vso[task.complete result=Failed;]DONE"
           exit 1
         else
           echo "No test failures detected."
         fi
+
+        #echo "Checking test result XML for failures..."
+        #TEST_XML=$(find "$(Pipeline.Workspace)" -name 'pytorch_test*.xml')
+        #if [ -z "$TEST_XML" ]; then
+        #  echo "##vso[task.logissue type=error]No $TEST_XML file found"
+        #  echo "##vso[task.complete result=Failed;]DONE"
+        #  exit 1
+        #fi
+
+        #if grep -q 'failures="[^0]' "$TEST_XML"; then
+        #  echo "##vso[task.logissue type=error]Test failures detected in $TEST_XML"
+        #  echo "##vso[task.complete result=Failed;]DONE"
+        #  exit 1
+        #else
+        #  echo "No test failures detected."
+        #fi
   - task: Bash@3
     displayName: Test Logs
     condition: always()
     inputs:
       targetType: inline
       script: |
-        cat pytorch-tests-${TEST_JOB_ID}.out || echo "No log found"
-  - task: PublishTestResults@2
-    displayName: 'Publish Results'
-    condition: succeededOrFailed()
-    inputs:
-      searchFolder: $(Pipeline.Workspace)
-      testResultsFormat: JUnit
-      testResultsFiles: '**/pytorch_test*.xml'
+        cat pytorch-vllm-${TEST_JOB_ID}.out || echo "No log found"
+        #  - task: PublishTestResults@2
+        #    displayName: 'Publish Results'
+        #    condition: succeededOrFailed()
+        #    inputs:
+        #      searchFolder: $(Pipeline.Workspace)
+        #      testResultsFormat: JUnit
+        #      testResultsFiles: '**/pytorch_test*.xml'
